name: schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
    # https://crontab.guru/

permissions:
  issues: write

jobs:
  make-issue:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4

      - name: 노드 셋업
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: index.js 실행
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node index.js